global:
  username: nhtlong
  project_name: "zaloai2022"
  name: "frameViT384-Tiny"
  save_dir: ./runs2
  use_fp16: true
  debug: false
  verbose: true
  SEED: 1337
  pretrained: null
  resume: null
  find_lr: false
data:
  name: ImageFolderFromCSV
  args:
    SIZE: 384
    train:
      CSV_PATH: data/train/labels_keyframes_train.csv
      IMG_DIR: data/train/keyframes/
      loader:
        batch_size: 64
        num_workers: 0
        shuffle: True
        drop_last: True
    val:
      CSV_PATH: data/train/labels_keyframes_test.csv
      IMG_DIR: data/train/keyframes/
      loader:
        batch_size: 64
        num_workers: 0
        shuffle: False
        drop_last: False
extractors:
  img_encoder:
    name: VitNetExtractor
    args:
      version: vit_tiny_patch16_384
      from_pretrained: True
      freeze: False
model:
  name: FrameClassifier
  args:
    NUM_CLASS: 2 
    EMBED_DIM: 1024
metric:
  - name: Accuracy
    args:
      label_key: "labels"
trainer:
  lr: 0.00036
  num_epochs: 100
  clip_grad: 10.0
  evaluate_interval: 1
  print_interval: 20
  save_interval: 1000
  accumulate_grad_batches: 4
callbacks:
  - name: ModelCheckpoint
    args:
      filename: "frameViT384Tiny-{epoch}-{val/Accuracy:.4f}"
      monitor: "val/Accuracy"
      verbose: True
      save_top_k: 3
      mode: max
  - name: EarlyStopping
    args:
      monitor: "val/Accuracy"
      min_delta: 0.0001
      patience: 15
      verbose: False
      mode: max
  - name: LearningRateMonitor
    args:
      logging_interval: step