global:
  username: nhtlong
  project_name: "zaloai2022"
  name: "frameB5-model"
  save_dir: ./runs
  use_fp16: true
  debug: false
  verbose: true
  SEED: 1337
  pretrained: null
  resume: null
  find_lr: False
data:
  name: ImageFolderFromCSV
  args:
    SIZE: 380
    train:
      CSV_PATH: data/train/labels_keyframes_train.csv
      IMG_DIR: data/train/keyframes/
      loader:
        batch_size: 16
        num_workers: 8
        shuffle: True
        drop_last: True
    val:
      CSV_PATH: data/train/labels_keyframes_test.csv
      IMG_DIR: data/train/keyframes/
      loader:
        batch_size: 32
        num_workers: 8
        shuffle: False
        drop_last: False
extractors:
  img_encoder:
    name: EfficientNetExtractor
    args:
      version: 5
      from_pretrained: True
      freeze: False
model:
  name: FrameClassifier
  args:
    NUM_CLASS: 2 
    EMBED_DIM: 1024
metric:
  - name: Accuracy
    args:
      label_key: "labels"
trainer:
  num_epochs: 10
  clip_grad: 10.0
  evaluate_interval: 1
  print_interval: 5
  save_interval: 1000
  accumulate_grad_batches: 4
  lr: 0.00043
callbacks:
  - name: ModelCheckpoint
    args:
      filename: "FrameClfB5-{epoch}-{val/Accuracy:.4f}"
      monitor: "val/Accuracy"
      verbose: True
      save_top_k: 3
      mode: max
  - name: EarlyStopping
    args:
      monitor: "val/Accuracy"
      min_delta: 0.0001
      patience: 15
      verbose: False
      mode: max
  - name: LearningRateMonitor
    args:
      logging_interval: step