global:
  pretrained: null
  save_path: null
  batch_size: 1
data:
  image_dir: null
  json_path: null
  crop_area: 1.0
  image_size: 288
extractors:
  img_encoder:
    name: EfficientNetExtractor
    args:
      version: 0
      from_pretrained: True
      freeze: True
model:
  name: VehColorClassifer
  args:
    NUM_CLASS: 8 # Num of unique colors
    EMBED_DIM: 768
