global:
  pretrained: null
  save_path: null
  batch_size: 32
data:
  SIZE: 380
  CSV_PATH: data/public/labels_bbox.csv
  IMG_DIR: data/public/faces/crop/
extractors:
  img_encoder:
    name: EfficientNetExtractor
    args:
      version: 7
      from_pretrained: False
      freeze: True
model:
  name: FrameClassifier
  args:
    NUM_CLASS: 2 
    EMBED_DIM: 1024