global:
  pretrained: null
  save_path: null
  batch_size: 32
data:
  SIZE: 380
  CSV_PATH: data/public/labels_bbox.csv
  IMG_DIR: data/public/faces/crop/
extractors:
  img_encoder:
    name: VitNetExtractor
    args:
      version: vit_tiny_patch16_384
      from_pretrained: True
      freeze: False
model:
  name: FrameClassifier
  args:
    NUM_CLASS: 2 
    EMBED_DIM: 1024